title:             yenos
email:             cpg0504@gmail.com
description:       IT 기술 블로그
author:            yenoss
baseurl:           /
url:               https://yenoss.github.io

# Social Profiles
twitter_username:  yenoss
github_username:   yenoss
facebook_username: yenoss

# code highlighter
highlighter: rouge

# add disqus
layout: default
comments: true
# other options

google_analytics:  UA-46795919-3

# Build settings
markdown:          kramdown
paginate:          7
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

