# Dependencies
markdown:         redcarpet
highlighter:      pygments

# # Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            yenos
tagline:          'A Jekyll theme'
description:      'develop'
url:              https://yenoss.github.io
baseurl:          /

author:
  name:           'yenoss'
  url:            https://twitter.com/mdo

paginate:         4

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/yenoss
